;; Global mode enable
(delete-selection-mode t)
(cua-selection-mode t) 
(auto-compression-mode 1)
(global-visual-line-mode 1)
(transient-mark-mode t)
;(global-hl-line-mode 1)
(global-auto-revert-mode t)
(recentf-mode 1)
(desktop-save-mode 1)
